### PR TITLE
Unifrom UI

### PR DESCRIPTION
**Pull request by ycybcnm**

### CODE REVIEW

**Comment by tigerman9854** [comment]
Once Chenyun pushes the latest changes (something to do with double sliders rather than int), I can fix the merge conflicts.  Most conflicts are with my previous pull request: #66

**Comment by ycybcnm** [comment]
I found the QSlider is not cannot emit a float signal, actually, it only works with integer, even if the object emits a float number, the number still will be rounded. One opinion is that define a new class that can do the float, I tried to use a new class called DoubleSlider, but it just has some fundamental function.  Another opinion is adding a drop-down menu, let users change the color by themselves, like followinng screenshots
If you prefer the first opinion, I will continue to implement DoubleSlider class.
Screenshot 222
Screenshot 224

**Comment by tigerman9854** [comment]
I'm fine with either option mentioned above.  Is there a reason we can't convert 0-255 (int8) to 0.0-1.0 (float32)?  You can subclass `QSlider` and upon the `valueChanged(int value)` signal, emit a custom signal: `valueChanged(float value)`.

`connect(this, &QSlider::valueChanged, this, [](int value){ emit valueChanged((float)value / 255.f)});`

**Comment by ycybcnm** [comment]
> I'm fine with either option mentioned above. Is there a reason we can't convert 0-255 (int8) to 0.0-1.0 (float32)? You can subclass `QSlider` and upon the `valueChanged(int value)` signal, emit a custom signal: `valueChanged(float value)`.
> 
> `connect(this, &QSlider::valueChanged, this, [](int value){ emit valueChanged((float)value / 255.f)});`

It can convert, but the question is QSlider only provides integer ranges.  No matter where I convert the int to float, it will lose the accuracy that users hope by using the QSlider.  For example, if the slider's range is 0-10, and the user wants 5.2, the user's cursor moves the slider handle to 5.2, the actual value still will be rounded to 5. The float signal still is the 5/255.f rather than 5.2/255.f.

**Comment by ycybcnm** [comment]
> > I'm fine with either option mentioned above. Is there a reason we can't convert 0-255 (int8) to 0.0-1.0 (float32)? You can subclass `QSlider` and upon the `valueChanged(int value)` signal, emit a custom signal: `valueChanged(float value)`.
> > `connect(this, &QSlider::valueChanged, this, [](int value){ emit valueChanged((float)value / 255.f)});`
> 
> It can convert, but the question is QSlider only provides integer ranges. No matter where I convert the int to float, it will lose the accuracy that users hope by using the QSlider. For example, if the slider's range is 0-10, and the user wants 5.2, the user's cursor moves the slider handle to 5.2, the actual value still will be rounded to 5. The float signal still is the 5/255.f rather than 5.2/255.f.

If there is no way to keep the accuracy, why not divide the 255.f before assigning to uniform?

**Review by tigerman9854 — APPROVED** [review]

**Pull request merged**
