### PR TITLE
Added xyz axes

### LINKED ISSUE #41: [10] Add axes and dimensions display
Blocked on: #40

### PR DESCRIPTION
**Pull request by tigerman9854**
Added axes to the bottom right.  I felt like putting them on the object would look annoying, so I didn't bother.
Closes #41

### CODE REVIEW

**Comment by tigerman9854** [comment]
image

**Comment by tigerman9854** [comment]
image

**Comment by zunyueseattle** [comment]
looks good!

**Review by richjoregonstate — APPROVED** [review]
Looks great :)

**Pull request merged**
