### PR TITLE
Change translation to matrix math

### LINKED ISSUE #32: [2] Change sceneMatrix to rotation matrix & translation matrix...
Keep a separate matrix for translation, rotation, scale, and view (matrix.perspective). Then, in the render() function, compute the overall transformation by multiplying these together each frame.

I think this is the right order of matrices.... Order does matter so try changing them around if it doesn't work.
FinalMat = view * scale * trans * rot

### PR DESCRIPTION
**Pull request by tigerman9854**
- Slightly reworked rotation and zoom to be more smooth
- Changed translation to use a matrix
- Added a method to compute the model matrix
- Updated tests

Closes #32

### CODE REVIEW

**Comment by tigerman9854** [comment]
image

**Comment by richjoregonstate** [comment]
Closes #43

**Comment by tigerman9854** [comment]
> 
> 
> Closes #43

Are you planning on pushing a change which does this to this branch?  I don't think I changed the controls.

**Review by richjoregonstate — APPROVED** [review]
Looks great.

Fun to see the changes!

**Pull request merged**
